# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e71734214f26f1970f079f3c0f8d22303152b8a827ff42a2920e180b8f597b5773ee340890b3305bceb2d073804d0aa024d23710fced3c84d2bd112726b63892

test:
  secret_key_base: 3e8df27acbbf3e11ab75da91f2c021bf8a69c6a3962c8e9f2b6407973a02533ad44535400ff5ccfa467643ab91b06908a87e000746b8fb16a2f6a2ff08fdc42c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
